config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "store#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_product(product)
        current_item = line_items.find_by(product_id: product.id)
        if current_item
            current_item.quantity += 1
        else
            current_item = line_items.build(product_id: product.id)
        end
        current_item
    end

    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize
  before_action :set_cart, only: %i[ show edit update destroy ]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)
    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil 
    respond_to do |format|
      format.html { redirect_to store_index_url,
        notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_index_url, notice: 'Your Cart is Empty'
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.haml
= render @cart

app/views/carts/_form.html.haml
= form_for @cart do |f|
  - if @cart.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cart.errors.count, "error")} prohibited this cart from being saved:"
      %ul
        - @cart.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/carts/edit.html.haml
%h1 Editing cart

= render 'form'

= link_to 'Show', @cart
\|
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%h1 Listing carts

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @carts.each do |cart|
      %tr
        %td= link_to 'Show', cart
        %td= link_to 'Edit', edit_cart_path(cart)
        %td= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.haml
%h1 New cart

= render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.haml
- if notice
  %p#notice.alert.alert-primary.alert-dismissible.fade.show= notice
.container-fluid.row
  .title.d-flex.justify-content-start.pt-5.pb-5
    %h3.m-2 Your Pragmatic Cart 
    %i.fa.fa-shopping-cart.fs-2.m-2{"aria-hidden" => "true"} 
  %table.table
    %thead.thead-dark
      %tr
        %th{:scope => "col"} #
        %th{:scope => "col"} Name
        %th{:scope => "col"} Quantity
        %th{:scope => "col"} Price
    %tbody
      - @cart.line_items.each do |item, index|
        %tr
          %th{:scope => "row"}= index
          %td= item.product.title
          %td= item.quantity
          %td= number_to_currency(item.total_price)
      %tr
        %th{:scope => "row"}
        %td
          %h5.mt-3 Total :-
        %td 
        %td
          %h5.mt-3= number_to_currency(@cart.total_price)
  
  .d-flex.w-100.justify-content-around
    = button_to 'Empty cart', @cart, method: :delete,
      data: { confirm: 'Are you sure?' },class:"btn btn-secondary m-3 text-right " 
    = button_to 'Checkout', new_order_path, 
      method: :get,                          
      class: "btn btn-secondary m-3 text-right"                      