config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "store#index"
end

app/views/layouts/_headers.html.haml
%nav.navbar.navbar-expand-lg.bg-light.sticky-top
  .container-fluid
    %a.navbar-brand.fs-2.hover-1{:href => "#"} Ethnic-Store
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item.hover-1
          = link_to  "Home" ,root_path, class:"nav-link active"
        %li.nav-item.hover-1
          -if @cart
            - @cart = Cart.find(session[:cart_id])
            = link_to  "Cart" ,cart_path(@cart), class:"nav-link "
        - if User.find_by(id: session[:user_id])
          %li.nav-item.dropdown
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
              User Name
            %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
              %li
                = link_to  "Orders" ,admin_path, class:"dropdown-item"
              %li
                = link_to  "Log out" ,logout_path, {:action => :destroy, class:"dropdown-item"}
        - else
          %li.nav-item.hover-1
            = link_to  "Admin_Login" ,login_path, class:"nav-link active"
      %form.d-flex{:role => "search"}
        %input.form-control.me-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
        %button.btn.btn-outline-success{:type => "submit"} Search

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Ecommerce
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    / CSS only
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}
    %link{:crossorigin => "anonymous", :href => "https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css", :integrity => "sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor", :rel => "stylesheet"}/
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    .container-fluid
      = render 'layouts/headers'
      .container.p-0.m-0
        = yield
    %script{:crossorigin => "anonymous", :integrity => "sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2", :src => "https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"}